# Site settings
title: "Jacob Nichols"
description: "My latest and greatest resume for the world to see."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Jacob Nichols"
resume_title:                   ""
resume_contact_email:           ""
resume_contact_telephone:       ""
resume_contact_address:         "742 Evergreen Terrace, Springfield"
resume_header_contact_info: "742 Evergreen Terrace, Springfield | 555-7334 | homerjsimpson@youremailaddress.com"
resume_header_intro: "<p>A fulfilling technical support position where my proven leadership, organizational, technical, and educational skills will translate to creating smooth running network systems..</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jnichols35/resume
  resume_twitter_url:           "http://twitter.com/jakenichols35"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/jacob-nichols-2a00a565/"
  # resume_instagram_url:  x       "insert your Instagram URL here"
  resume_website_url:           "http://jnichols.io"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
